name: Update

on:
  push:
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 17
          distribution: adopt
          cache: gradle

      - name: Init
        run: |
          chmod +x ./gradlew
          ./gradlew
          git config --global user.email action@github.com
          git config --global user.name github-actions

      - name: Check
        if: false
        run: ./gradlew check

      - name: Format
        run: ./gradlew format

      - name: Commit data
        run: |
          git commit -m "registry sync" -a || true
          git push || true
